name: 'Terraform GKE Provision'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3

    - name: Setorp/setup-terraform@v2
      with: up Terraform'
      uses: hashic
      terraform_version: 1.5.6 # Set the version you need
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: 'Authenticate to GCP'
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > account.json
        gcloud auth activate-service-account --key-file=account.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
