name: 'Terraform GKE Provision'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6 # Use the version you need

    - name: 'Authenticate to GCP'
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${GCP_SERVICE_ACCOUNT_KEY}" | base64 --decode > account.json
        gcloud auth activate-service-account --key-file=account.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
